// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/ideal_body_fat.proto

package fitness_tracker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bump struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age               *Bump_AgeRange       `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	BodyFatPercentage []*Bump_BodyFatRange `protobuf:"bytes,3,rep,name=body_fat_percentage,json=bodyFatPercentage,proto3" json:"body_fat_percentage,omitempty"`
}

func (x *Bump) Reset() {
	*x = Bump{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ideal_body_fat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bump) ProtoMessage() {}

func (x *Bump) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ideal_body_fat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bump.ProtoReflect.Descriptor instead.
func (*Bump) Descriptor() ([]byte, []int) {
	return file_proto_ideal_body_fat_proto_rawDescGZIP(), []int{0}
}

func (x *Bump) GetAge() *Bump_AgeRange {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *Bump) GetBodyFatPercentage() []*Bump_BodyFatRange {
	if x != nil {
		return x.BodyFatPercentage
	}
	return nil
}

type Bumps struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bump []*Bump `protobuf:"bytes,1,rep,name=bump,proto3" json:"bump,omitempty"`
}

func (x *Bumps) Reset() {
	*x = Bumps{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ideal_body_fat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bumps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bumps) ProtoMessage() {}

func (x *Bumps) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ideal_body_fat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bumps.ProtoReflect.Descriptor instead.
func (*Bumps) Descriptor() ([]byte, []int) {
	return file_proto_ideal_body_fat_proto_rawDescGZIP(), []int{1}
}

func (x *Bumps) GetBump() []*Bump {
	if x != nil {
		return x.Bump
	}
	return nil
}

type Bump_AgeRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min *int64 `protobuf:"varint,1,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max *int64 `protobuf:"varint,2,opt,name=max,proto3,oneof" json:"max,omitempty"`
}

func (x *Bump_AgeRange) Reset() {
	*x = Bump_AgeRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ideal_body_fat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bump_AgeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bump_AgeRange) ProtoMessage() {}

func (x *Bump_AgeRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ideal_body_fat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bump_AgeRange.ProtoReflect.Descriptor instead.
func (*Bump_AgeRange) Descriptor() ([]byte, []int) {
	return file_proto_ideal_body_fat_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Bump_AgeRange) GetMin() int64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *Bump_AgeRange) GetMax() int64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type Bump_BodyFatRange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description *string  `protobuf:"bytes,1,opt,name=description,proto3,oneof" json:"description,omitempty"`
	HealthRisk  *string  `protobuf:"bytes,2,opt,name=health_risk,json=healthRisk,proto3,oneof" json:"health_risk,omitempty"`
	Min         *float32 `protobuf:"fixed32,3,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max         *float32 `protobuf:"fixed32,4,opt,name=max,proto3,oneof" json:"max,omitempty"`
}

func (x *Bump_BodyFatRange) Reset() {
	*x = Bump_BodyFatRange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ideal_body_fat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bump_BodyFatRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bump_BodyFatRange) ProtoMessage() {}

func (x *Bump_BodyFatRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ideal_body_fat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bump_BodyFatRange.ProtoReflect.Descriptor instead.
func (*Bump_BodyFatRange) Descriptor() ([]byte, []int) {
	return file_proto_ideal_body_fat_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Bump_BodyFatRange) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Bump_BodyFatRange) GetHealthRisk() string {
	if x != nil && x.HealthRisk != nil {
		return *x.HealthRisk
	}
	return ""
}

func (x *Bump_BodyFatRange) GetMin() float32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *Bump_BodyFatRange) GetMax() float32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

var File_proto_ideal_body_fat_proto protoreflect.FileDescriptor

var file_proto_ideal_body_fat_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x64, 0x65, 0x61, 0x6c, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x5f, 0x66, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf2, 0x02, 0x0a,
	0x04, 0x42, 0x75, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x75, 0x6d, 0x70, 0x2e, 0x41, 0x67, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x42, 0x0a, 0x13, 0x62, 0x6f, 0x64, 0x79, 0x5f,
	0x66, 0x61, 0x74, 0x5f, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x42, 0x75, 0x6d, 0x70, 0x2e, 0x42, 0x6f, 0x64, 0x79,
	0x46, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x11, 0x62, 0x6f, 0x64, 0x79, 0x46, 0x61,
	0x74, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x1a, 0x48, 0x0a, 0x08, 0x41,
	0x67, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x15,
	0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x06, 0x0a,
	0x04, 0x5f, 0x6d, 0x61, 0x78, 0x1a, 0xb9, 0x01, 0x0a, 0x0c, 0x42, 0x6f, 0x64, 0x79, 0x46, 0x61,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a,
	0x0b, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x72, 0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x69, 0x73, 0x6b,
	0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x6d, 0x61,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x48, 0x03, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x88, 0x01,
	0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x72, 0x69, 0x73,
	0x6b, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x61,
	0x78, 0x22, 0x22, 0x0a, 0x05, 0x42, 0x75, 0x6d, 0x70, 0x73, 0x12, 0x19, 0x0a, 0x04, 0x62, 0x75,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x42, 0x75, 0x6d, 0x70, 0x52,
	0x04, 0x62, 0x75, 0x6d, 0x70, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x66, 0x6f, 0x72, 0x74, 0x73, 0x6f, 0x6e, 0x2f, 0x66, 0x69, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ideal_body_fat_proto_rawDescOnce sync.Once
	file_proto_ideal_body_fat_proto_rawDescData = file_proto_ideal_body_fat_proto_rawDesc
)

func file_proto_ideal_body_fat_proto_rawDescGZIP() []byte {
	file_proto_ideal_body_fat_proto_rawDescOnce.Do(func() {
		file_proto_ideal_body_fat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ideal_body_fat_proto_rawDescData)
	})
	return file_proto_ideal_body_fat_proto_rawDescData
}

var file_proto_ideal_body_fat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ideal_body_fat_proto_goTypes = []interface{}{
	(*Bump)(nil),              // 0: Bump
	(*Bumps)(nil),             // 1: Bumps
	(*Bump_AgeRange)(nil),     // 2: Bump.AgeRange
	(*Bump_BodyFatRange)(nil), // 3: Bump.BodyFatRange
}
var file_proto_ideal_body_fat_proto_depIdxs = []int32{
	2, // 0: Bump.age:type_name -> Bump.AgeRange
	3, // 1: Bump.body_fat_percentage:type_name -> Bump.BodyFatRange
	0, // 2: Bumps.bump:type_name -> Bump
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ideal_body_fat_proto_init() }
func file_proto_ideal_body_fat_proto_init() {
	if File_proto_ideal_body_fat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ideal_body_fat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bump); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ideal_body_fat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bumps); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ideal_body_fat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bump_AgeRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ideal_body_fat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bump_BodyFatRange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_ideal_body_fat_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_proto_ideal_body_fat_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ideal_body_fat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ideal_body_fat_proto_goTypes,
		DependencyIndexes: file_proto_ideal_body_fat_proto_depIdxs,
		MessageInfos:      file_proto_ideal_body_fat_proto_msgTypes,
	}.Build()
	File_proto_ideal_body_fat_proto = out.File
	file_proto_ideal_body_fat_proto_rawDesc = nil
	file_proto_ideal_body_fat_proto_goTypes = nil
	file_proto_ideal_body_fat_proto_depIdxs = nil
}
