version: '3.7'

services:

  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
    # entrypoint: ['/home/papg/boot.sh']
    # volumes:
    #   - './server:/home/papg'
    # ports:
    #   - 5000:5000
    # environment:
    #   - FLASK_APP=papg_backend.py
    #   - LC_ALL=C.UTF-8
    #   - LANG=C.UTF-8
    #   - PORT=5000
    #   - DATABASE_URL=postgresql://postgres:postgres@papg-db:5432/dev
    # depends_on:
    #   - papg-db

  # papg-db:
  #   build:
  #     context: ./server/db
  #     dockerfile: Dockerfile
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres



  client:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    ports:
      - 3000:80
    # depends_on: 
    #   - server

