version: '3.7'

services:

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    entrypoint: ['./main']
    ports:
      - 5000:8000
    environment:
      - DB_URI=postgresql://postgres:postgres@db:5432/dev
      - APP_ENV=dev
      - DB_HOST=db
      - DB_NAME=dev
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres



  client:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
    environment:
      - NODE_OPTIONS=--max_old_space_size=4096
    ports:
      - 3000:80
    depends_on: 
      - server

